#!/bin/bash

main(){

  declare +g wm_path script_body=""
  declare -g tmp_i3sock tmp_xevent_script

  if [[ -x ${wm_path:=$(command -v "$1")} ]]
    then set "$wm_path" "${@:2}"
    else ERX "not a valid window manager command '$*'"
  fi

  Xephyr -resizeable -ac -noreset :"${_o[display]:-2}" &

  command -v xrandr >/dev/null   && script_body+="xrandr"$'\n'
  [[ ${_o[wallpaper-command]} ]] && script_body+="${_o[wallpaper-command]}"$'\n'

  [[ $script_body ]] && {
    
    tmp_xevent_script=$(mktemp)
    printf '%s\n' "#!$BASH" "$script_body" > "$tmp_xevent_script"
    chmod +x "$tmp_xevent_script"

    {
      sleep .2
      DISPLAY=:"${_o[display]:-2}" "$tmp_xevent_script"
      # https://github.com/ritave/xeventbind/
      sleep .1
      command -v xeventbind >/dev/null \
        && DISPLAY=:"${_o[display]:-2}" xeventbind resolution "$tmp_xevent_script" >/dev/null
    } &

  }

  sleep .1

  tmp_i3sock=$(mktemp)
  DISPLAY=:"${_o[display]:-2}" I3SOCK="$tmp_i3sock" "$@"
}

__dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")") #bashbud
source "$__dir/_init.sh"                              #bashbud
