#!/bin/bash

main(){

  wm_path=$(command -v "$1")

  [[ -x $wm_path ]] || ERX "not a valid window manager command '$*'"

  set "$wm_path" "${@:2}"

  Xephyr -resizeable -name Xephyr -ac -noreset :"${_o[display]:-2}" &

  sleep 0.1


  [[ ${_o[wallpaper-command]} ]] \
    && DISPLAY=:"${_o[display]:-2}" bash -c " ${_o[wallpaper-command]}"

  # https://github.com/ritave/xeventbind/
  { command -v xeventbind  ;} >/dev/null && {

    command -v xrandr >/dev/null   && script_body+="xrandr"$'\n'
    [[ ${_o[wallpaper-command]} ]] && script_body+="${_o[wallpaper-command]}"$'\n'

    [[ $script_body ]] && {
      temp_xeventbind_script=$(mktemp)
      echo "$script_body" > "$temp_xeventbind_script"

      chmod +x "$temp_xeventbind_script"

      DISPLAY=:"${_o[display]:-2}" xeventbind resolution "$temp_xeventbind_script" >/dev/null
    }
  } &

  tmp_i3sock=$(mktemp)
  DISPLAY=:"${_o[display]:-2}" I3SOCK="$tmp_i3sock" "$@"

  [[ -f $temp_xeventbind_script ]] && rm "$temp_xeventbind_script"
  [[ -f $tmp_i3sock ]] && rm "$tmp_i3sock"

  pkill -P $$
}

__dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")") #bashbud
source "$__dir/_init.sh"                              #bashbud
