#!/bin/bash

main(){

  declare +g wm_path script_body=""
  declare -g tmp_i3sock tmp_xevent_script

  wm_path=$(command -v "$1")

  [[ -x $wm_path ]] || ERX "not a valid window manager command '$*'"

  set "$wm_path" "${@:2}"

  Xephyr -resizeable -name Xephyr -ac -noreset :"${_o[display]:-2}" &

  sleep 0.1

  [[ ${_o[wallpaper-command]} ]] \
    && DISPLAY=:"${_o[display]:-2}" "$BASH" -c " ${_o[wallpaper-command]}"

  # https://github.com/ritave/xeventbind/
  command -v xeventbind >/dev/null && {

    command -v xrandr >/dev/null   && script_body+="xrandr"$'\n'
    [[ ${_o[wallpaper-command]} ]] && script_body+="${_o[wallpaper-command]}"$'\n'

    [[ $script_body ]] && {
      tmp_xevent_script=$(mktemp)
      printf '%s\n' "#!$BASH" "$script_body" > "$tmp_xevent_script"

      chmod +x "$tmp_xevent_script"

      DISPLAY=:"${_o[display]:-2}" xeventbind resolution "$tmp_xevent_script" >/dev/null &
    }
  } 

  tmp_i3sock=$(mktemp)
  DISPLAY=:"${_o[display]:-2}" I3SOCK="$tmp_i3sock" "$@"
}

__dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")") #bashbud
source "$__dir/_init.sh"                              #bashbud
